### ISSUE TITLE
How can I loop over each node and select it. 

### ISSUE THREAD

**Issue by webfriend13** [jonmiles/bootstrap-treeview#102]
I am using following array to load the data into the treeview. 

var tree = [
  {
    text: "Parent 1",
    id: 'n1',
    nodes: [
      {
        text: "Child 1",
        id: 'n2',
        nodes: [
          {
            text: "Grandchild 1"
            id: 'n3'
          },
          {
            text: "Grandchild 2"
            id: 'n4'
          }
        ]
      },
      {
        text: "Child 2"
            id: 'n5'
      }
    ]
  },
  {
    text: "Parent 2"
            id: 'n6'
  },
 
];

To the treeview I have added a checkbox, now user can select some nodes and save the information. While saving, I save the id field of each node. Now when the treeview is loaded next time, I want to check the checkbox against each node. How can I achieve this ??  Please help

**Comment by jonmiles** [comment]
You should be defining this information as part of the node's state in the initial data provider.

```javascript
{
  text: 'Parent 1',
  state: {
    checked: true
  }
}
```

Documented [here](https://github.com/jonmiles/bootstrap-treeview#statechecked)

**Comment by webfriend13** [comment]
@jonmiles : Thank you for quick reply. I do not have this information while forming the data source for the grid. Based on user interaction with the application, I get an array which contains some id's which I must select\check. Ideally in such case, I should loop over data-source, get the node by custom property or id and then set the checked or selected property. I do not want to set this property at design time.

**Comment by jonmiles** [comment]
@webfriend13 Your approach is wrong.  You should be managing the external data source and not the tree view.  For example, when changes occur in your application you should be capturing this and running some basic CRUD type operations to manipulate your data source.  The tree should then be refreshed by generating your tree data from your managed data source.  In this way you are able to populate the tree data with the various state variables e.g. `checked: true`
