### ISSUE TITLE
Method to retrieve nodes by any node property

### ISSUE THREAD

**Issue by jonmiles** [jonmiles/bootstrap-treeview#103]
Current implementation only allows users to retrieve a node by the internal node tracking id.  In most cases (#89) this is not suitable as the id is auto generated and can potentially change on subsequent renders.

The functionality is already available internally via `findNodes` so we just need to expose this via the API.

**Comment by TimYi** [comment]
Yes, it's a very important feature.

**Comment by jonmiles** [comment]
Replaced `getNode(nodeId)` with `findNodes(pattern, field)` which allows pattern matching on any node field.

Example usage:
```
var tree = $('#treeview1').treeview(true);
tree.findNodes('Parent 1', 'text');
```

Also updated all API methods to accept an array of nodes instead of various identifiers.  Results of findNodes can be passed directly into any method that accepts nodes as an argument.
