### ISSUE TITLE
Is there a way to get a list of nodes that are checked or unchecked?

### ISSUE THREAD

**Issue by TaimoorHasnie** [jonmiles/bootstrap-treeview#106]
Hi,
In my treeview I have a checkbox in each node. Based on the treeview I have to create a filtering system. So is there a way(method) to find out which nodes have been checked or unchecked.

Thanks,
Taimoor.

**Comment by jonmiles** [comment]
Yes, `getChecked` and `getUnchecked`. Please read the doc.

**Comment by TaimoorHasnie** [comment]
I have confirmed and checked again...I am sorry but I don't see any method
named getChecked or getUnchecked...I just search the repo and found the
methods in the changelog but not in the docs. Can you please update the
docs.

Thanks,
Taimoor.

I am looking at this page
https://github.com/jonmiles/bootstrap-treeview/blob/master/README.md
