### ISSUE TITLE
Cant append <li class="list-group-item node-tree node-checked">  in onNodeChecked event.

### ISSUE THREAD

**Issue by ian-patel** [jonmiles/bootstrap-treeview#113]
### Append not working
      <li class="list-group-item node-tree node-checked" data-nodeid="9" style="color:undefined;background-color:undefined;">
          <span class="indent"></span>
          <span class="icon glyphicon"></span>
          <span class="icon check-icon glyphicon glyphicon-check"></span>
          text12345
      </li>
Onchecked event i want to add spinner after text
     
     onNodeChecked: function(event, node) {
          $("[data-nodeid=" + node.nodeId + "]").append('<i class="fa fa-spinner fa-spin"></i>');
     }
I want to add sippner icon after ``node.text``.  

after checked event, it should be 

     <li class="list-group-item node-tree node-checked" data-nodeid="9" style="color:undefined;background-color:undefined;">
          <span class="indent"></span>
          <span class="icon glyphicon"></span>
          <span class="icon check-icon glyphicon glyphicon-check"></span>
          text12345
          <i class="fa fa-spinner fa-spin"></i>
      </li>

Thanks!

**Comment by jonmiles** [comment]
Possibly related to #76 where the DOM is being recreated after state changes.  This is being worked on and expected in the next release.  There is a branch 'feature/76-avoid-dom-recreation' that you could try.
