### ISSUE TITLE
Node selectable: false, hide select icon

### ISSUE THREAD

**Issue by BenasPaulikas** [jonmiles/bootstrap-treeview#114]
If my node is not selectable why do I need select icon ?

**Comment by jonmiles** [comment]
Please can you expand. Are you trying to report a bug?

**Comment by BenasPaulikas** [comment]
For now yii2 use bootstrap3 as default? What will be when bootstrap4 will be released ?

**Comment by jonmiles** [comment]
Another random question ?

**Comment by BenasPaulikas** [comment]
I mean like I have tree:
Products
  A
  B
Services
  A
  B

How do I disable that Products and Services would be without selection ?

**Comment by jonmiles** [comment]
It's still not clear what you're asking, but I'll have go at trying to answer.

If you want Products + Services nodes to be non-selectable, use `selectable: false`.  if you want them to be disabled use `state.disabled: false`.  Be aware that If a node is disabled, it will be collapsed and it's children will not be displayed.  

If you want a non-selectable node to look like it's disabled but still slow it's children, then you could play around with the node level properties `color` and `backColor`.

**Comment by BenasPaulikas** [comment]
![asd](https://cloud.githubusercontent.com/assets/6473565/9382580/e76af03a-474a-11e5-8fe0-e1ddfa2de71b.png)
I want node1 and node2 to be extendable only. To remove <span class="icon check-icon glyphicon glyphicon-unchecked"></span> from them

**Comment by jonmiles** [comment]
If you don't want check boxes then set `showCheckbox: false'.  Although this is global and I don't think you can set this at the node level.

**Comment by BenasPaulikas** [comment]
Well I will do hack then to hide these 2 icons

**Comment by BenasPaulikas** [comment]
What about changing https://github.com/jonmiles/bootstrap-treeview/blob/master/src/js/bootstrap-treeview.js#L575

'''
classList.push(_this.options.uncheckedIcon);
'''

to

'''
if(typeof node.selectable != 'undefined' && !node.selectable) classList.push(_this.options.uncheckedIcon);
''''

**Comment by BenasPaulikas** [comment]
https://github.com/jonmiles/bootstrap-treeview/blob/master/src/js/bootstrap-treeview.js#L578 adding 

adding 
    if(typeof node.selectable == 'undefined' || node.selectable == true)
before line 578 did the work. @jonmiles do you approve ?

**Comment by jonmiles** [comment]
No this is a very specific use case and I think you're confusing selectable with checkable.  

The checkbox icon (state `checked`) and the node state `selectable` are two different states.  It should not be the case that a non-selectable node can not be checked, or displaed with a checked state.

As `selectable` is not defined by default, you are requiring users to add this additional property in order to use check boxes.

**Comment by dineshnagarit** [comment]
BenasPaulikas  is right here what if I just want to show the check box for child nodes only why would I need to show the checkboxes on parent node also?

**Comment by cnhans** [comment]
that should need to add a switch (checkbox) to the parent node.
