### ISSUE TITLE
1.2.0 and JQuery On Events Stopped Working

### ISSUE THREAD

**Issue by mxmissile** [jonmiles/bootstrap-treeview#122]
I just upgraded my install to 1.2.0, now my jquery on events stopped firing.

This does not work:
```javascript
$('#tree').on('nodeSelected', function (event, node) {
     console.log(node);
 });
```

However, this does work:
```javascript
 $('#tree').treeview({
          onNodeSelected: function(event, node) {
                console.log(node);
     }
  });
```
Not sure what I did to cause this, any ideas?

running jquery 2.1.4, and bootstrap 3.3.5

**Comment by jonmiles** [comment]
That's strange, I did make some changes to the plugin wrapper and the way it exposes the treeview instance to the caller in 1.2.  Although I'm not sure how this would have affected your events in this way.

I've just run a very basic test against the 1.2 online demo and it appears to work.  You can try it yourself, visit [1.2 online demo](http://jonmiles.github.io/bootstrap-treeview/) and copy the following into the console.

```javascript
$('#treeview1').on('nodeSelected', function (event, data) {
  console.log('You clicked '  +data.text);
});
```

**Comment by mxmissile** [comment]
I got something else going on, I ran the code in the console on my app and the event fired just fine. Will close this thanks Jon.

**Comment by mxmissile** [comment]
Just a head's up on what I did wrong in case anyone else runs into this, I was wiring up the event outside of a callback. Not sure if this is expected behavior or not as it worked in previous versions outside of a callback.

```javascript
$.getJSON('/nodes', function(data) {
  $('#tree').treeview({ data: data  });
});

$('#tree').on('nodeSelected', function(event, node) {
   console.log('test');
});
```
vs
```javascript
$.getJSON('/nodes', function(data) {
  $('#tree').treeview({ data: data  });
  $('#tree').on('nodeSelected', function(event, node) {
     console.log('test');
  });
});
```

**Comment by jonmiles** [comment]
Aha, that makes sense!  Although it's not the fact that it's in the callback that makes it work, rather the order you're call them.  The events should be registered after the treeview has been initialized, as re-initializing the tree will discard any previously registered events.
