### ISSUE TITLE
JSON data and simple quotes for tags

### ISSUE THREAD

**Issue by AntonyLopez** [jonmiles/bootstrap-treeview#125]
When JSON is used to load data into the tree if you try to put TAGS on format "tags":"['4']" fails ,I understand that it's because single quotes are not allowed in JSON. Is there any workarround? or simply can not use the property TAGS with JSON

**Comment by jonmiles** [comment]
You don't put the array in quotes, just the array elements.

```javascript
"tags": ["4"]
```
