### ISSUE TITLE
npm deps remove

### ISSUE THREAD

**Issue by io3** [jonmiles/bootstrap-treeview#126]
I use npm to install this package, but the deps is unneed. Can you remove the deps?

**Comment by jonmiles** [comment]
No, they are all needed!

**Comment by io3** [comment]
why ?

**Comment by jonmiles** [comment]
To build, test and run the project locally!

**Comment by io3** [comment]
Just development need, but it's unneed when we only require the module. You can move `express/ejs/phantomjs` to `devDependencies`.
