### ISSUE TITLE
getSelected bug?

### ISSUE THREAD

**Issue by goffyara** [jonmiles/bootstrap-treeview#129]
In data:
```javascript
  state: {
    selected: true
  },
```
if get all selected nodes, 
```javascript
$('#tree').treeview('getSelected')
```
i see 
> Array [  ]

if i click and selected any nodes, then do
```javascript
$('#tree').treeview('getSelected')
```
i see only clicked nodes. Although all of them has class "node-selected"

**Comment by jonmiles** [comment]
Impossible.  Perhaps you have something wrong with your code, I would suggest a timing issue such as calling `getSelected` before the tree view has had chance to initialise.

**Comment by valiradut** [comment]
"getSelected" return selected item on the tree, not the checked items (if using checkboxes).

is there a method to get all the checked items?

**Comment by jonmiles** [comment]
Yes there is an equivalent method named `getChecked`, it is however unfortunately missing from the documentation.

**Comment by valiradut** [comment]
Thank you, 
I was close to replace this treeview solution in absence of that kind of method. 

Please, add "getChecked" to docs.

**Comment by Dsupreme** [comment]
This went missing from the documentation again. Please add it.
