### ISSUE TITLE
Need more methods

### ISSUE THREAD

**Issue by efureev** [jonmiles/bootstrap-treeview#130]
Method, whose change DOM-data of this node: redraw item node, expl:
```
function (undefined, item) {
item.tags = ['12','1'];
   $('#tree').treeview('redraw',item);
   // or
   item.redraw();
}
```

```
<..>.getDomNode(item); // return jQuery DOM object (or not jQuery)
```

```
<>.onHover( // item (<li>)
   function(){}, // on
   function(){} // off
);
```

**Comment by jonmiles** [comment]
There will be some additional methods added in due course e.g. add, update, remove as well as event hooks in order to custom nodes post render.  The rest can be done using jQuery.
