### ISSUE TITLE
Can it work with existing html list and not json data?

### ISSUE THREAD

**Issue by cleocadio** [jonmiles/bootstrap-treeview#132]
I have a huge list generated in asp code, not json, When I initialise it does not work. 
Does it only work with json?

**Comment by jonmiles** [comment]
It will work with a valid JavaScript object, or equivalent JSON representation.

**Comment by cleocadio** [comment]
Humm, ok, I meant with a static html list

My Example

I Tried this:

<div id="allocationtree" class="treeview">
							<ul>
								<li>Coffee</li>
								<li>Tea</li>
								<li>Milk</li>
							</ul>
		        </div>


initialised like this

$(document).ready(function () {
  
   $("#allocationtree").treeview();


});

and this was the output

<div id="allocationtree" class="treeview"><ul class="list-group"></ul></div>

no list items whatsoever

Am I missing Something? 

Thanks in advance

**Comment by mxmissile** [comment]
A standard html list is not JSON. You will have to convert it to valid JSON first.

**Comment by cleocadio** [comment]
thanks.
