### ISSUE TITLE
need the ability to prevent unselect

### ISSUE THREAD

**Issue by mykeblack** [jonmiles/bootstrap-treeview#139]
Am using the treeview and need to be able to make it so that once a node is selected, you cannot click on it again to unselect it, (but retain the ability to unselect a node when you select a different node). 

So basically a global option is required - something like 'min-selections' so that you can set this to '1' to prevent people from having less than 1 selection. A 'max-selections' option would also be useful for multiselect trees so you can make it so that users cannot select more than X nodes in a single tree.

if min-selections is set to greater than 0, then you cannot unselect any node until you have reached more  than that number of selections.

**Comment by hha-clarcert** [comment]
I'd like to see this functionality as well. I tried using a nodeUnselected handler that reselects the node immediately after it is unselected but unfortunately it stayed unselected.

**Comment by JackyGe** [comment]
Same here. I want this functionality.

**Comment by ComradePashka** [comment]
I have same trouble, read this issue and solve it by setting treeview multiSelect to true and adding code  below to onNodeSelected handler:

  if (selectedNodes = $(this).treeview('getSelected')) {
    selectedNodes.forEach(function(node) {
      if (node.data != item.data) $(this).treeview('unselectNode', node.nodeId);
    }, this);
  }

so at onNodeUnselected you can handle deselect to keep selection:

  if ($(this).treeview('getSelected').length == 0) {
    $(this).treeview('selectNode', item.nodeId)
  }

actually when multiSelect is false it is also works but have some weird event rotations I unable to realize how to fix
anyway I agreed with other peoples that it is better to have such behavior natively.

**Comment by gavvvr** [comment]
Would be nice to have such feature

**Comment by jonmiles** [comment]
This is covered by #173
