### ISSUE TITLE
add value to node

### ISSUE THREAD

**Issue by celtic34fr** [jonmiles/bootstrap-treeview#140]
Hello,

great job, but I found one thing that was missing for my use.
You generate value nodeId sequentially, but sometimes it is more useful to assign a value to each node as a codification.

To make this, I add to Tree.prototype.buildTree after line > .attr ('data-nodeId' node.nodeId) <, the following line > .attr ('data-value "node.value) <

I pass the attribute 'value' in the datas that enable me to initialize the object treeView. 
Having made a test on the onSelectedNode event, I could retrieve
the value of the attribute 'value' in the case of a single selection without problems
I use the following code:
$ ('# Tree'). One ('nodeSelected', function (even, node) {
alert ('node' + node.value + 'was selected');
});

I leave you the decision to integrate this improvement in the future version of TreeView.

**Comment by jonmiles** [comment]
I assume you need `value` in order to then search the DOM for your element?

In which case I believe your issue is related to #103 which is intended to remove the requirement and dependency of the generated `id` which is required internally.

**Comment by celtic34fr** [comment]
is not totaly for searching in DOM.
I'm building a family list with sub-items, it's easier for me to get a value, which may be a data base record ID.
If the creation of node ID is simply made as described in the discussion, this could answer my needs.

I'm waiting the 1.3.0 issues to see that.

**Comment by jonmiles** [comment]
Then I don't think you need to add your additional line, the node is simply a JavaScript object and as such is designed to be expanded.  You can add as many new properties as you like, they will always be available as part of the node object passed around.

**Comment by celtic34fr** [comment]
As i say, i've modified the bloc Tree.prototype.buildTree by adding line to set the new attribute data-value.
According to this modification, i can get that attribut in onSelectedNode and onUnselectedNode event. that's fit to my need for the moment. My goal was to propose a change that could be used by other than I.

**Comment by jonmiles** [comment]
Great, I'm glad you managed to work it out for now.  But you still don't need to add that line in order to access additional node values, it just pollutes the DOM.

Closing, #103 will help make this easier in the furure
