### ISSUE TITLE
Filtering Nodes on Search

### ISSUE THREAD

**Issue by rkhmelichek** [jonmiles/bootstrap-treeview#141]
I'm using the treeview plugin to display some fairly long hierarchical lists.
The search feature changes the color/expands the matching nodes, which is nice, but since we have so many nodes, it might be colored off-screen.

I would like to have a mode where the search feature would narrow the results to only display the nodes that match (and all children in case the parent matches - but that should be configurable).

I'm wondering whether this should be a feature of the plugin, or should that be external to the plugin. I could filter the JSON model by the text search and then re-build the treeview.
When the user clears the text search, I could re-build the treeview from the original model.

I could take a shot at implementing it inside the plugin if it makes sense to do so.

Thanks,
-Roman

**Comment by jonmiles** [comment]
Thanks Roman.  

Actually I already have #47 to implement this functionality, which in turn is dependent on me finishing #76.  It's just I haven't had much spare time recently.

**Comment by jonmiles** [comment]
Closing, feature will be tracked by #47
