### ISSUE TITLE
How to add custom data-attributes?

### ISSUE THREAD

**Issue by softwarea** [jonmiles/bootstrap-treeview#142]
I am using bootstrap-treeview 1.2.0.

My goal is to add custom data-attributes to my list items' markup, e.g.

<li class="list-group-item node-tree" data-id="100" data-type="user" ...>

[{"text":"Root","icon":null,"data-id":1,"data-type":"branch","nodes":[{"text":"Steve","icon":null,"data-id":17, "data-type":"user","nodes":...

To me the JSON looks good. But none of my data-attributes gets rendered in the markup.

Any ideas?

**Comment by jonmiles** [comment]
That's not how it works, neither intended or desired functionality.

**Comment by softwarea** [comment]
I was following this link: https://github.com/bcopy/bootstrap-treeview/commit/7754cd7fc4f328b0fda25255ced1745cc8be541b?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

Just realized this is another fork. Sorry about that.
