### ISSUE TITLE
Expand / Collapse on node click

### ISSUE THREAD

**Issue by THenkeDE** [jonmiles/bootstrap-treeview#148]
I would like some internal Option for this behaviour:

If i have a tree where not every node has an href, i would like to click on the entire node to expand / collapse.

For the moment i add the "nohref" property to those nodes, check for it and, if present, call the actions.

```Javascript
	onNodeSelected: function(event, data) {
		if( data.nohref ) {			$(this).treeview('toggleNodeExpanded',data.nodeId).treeview('unselectNode',data.nodeId);
		}
	}
```

Maybe this is of use for someone else

**Comment by ypnos-web** [comment]
From your code it looks like you are trying to achive what you already get when setting 'selectable' to false on all nodes.

**Comment by THenkeDE** [comment]
thx for mentioning, i recogniced just half an hour after my post.
