### ISSUE TITLE
Is there anyway to uncheck multiple nodes in one shot?

### ISSUE THREAD

**Issue by rgelb** [jonmiles/bootstrap-treeview#151]
I need to check/uncheck child nodes when the parent is toggled.  I've implemented it as in issue 107.

    checkChildNodes: function(cssSelector, node) {
        var children = node.nodes;
        if (children) {
            for (var i = 0; i < children.length; i++) {
                var childNode = children[i];
                var nodeId = childNode['nodeId'];
                $(cssSelector).treeview('checkNode', nodeId);
            }
        }
    }

However, this is really slow.  If I have 30 child nodes, it takes over 1.2 seconds to check them all.  Is there a faster way of doing this?

**Comment by ypnos-web** [comment]
If you look at the code you see that all these methods also support multiple arguments. The real issue here is a lack of documentation.

E.g. you can write:
````javascript
var tree = $("#example").treeview(true);
tree.unselectNode(tree.getSelected());
````

(This example unselects all selected notes. You can do likewise with checked, disabled, etc.)

**Comment by rgelb** [comment]
True, this example does work, but the following one does not:

            var parentNode = ... // some node with several child nodes

            var tree = $("#example").treeview(true);
            tree.uncheckNode(parentNode.nodes, { silent: true });

For whatever reason, passing in the parentNode.nodes array doesn't seem to
do the trick.  But if I pass in tree.getChecked() - that does work, even
though it seems like the same array.



On Thu, Dec 10, 2015 at 2:49 AM, ypnos-web <notifications@github.com> wrote:

> If you look at the code you see that all these methods also support
> multiple arguments. The real issue here is a lack of documentation.
>
> E.g. you can write:
>
> var tree = $("#example").treeview(true);tree.unselectNode(tree.getSelected());
>
> (This example unselects all selected notes. You can do likewise with
> checked, disabled, etc.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jonmiles/bootstrap-treeview/issues/151#issuecomment-163577258>
> .
>



-- 

Regards,
Robert

**Comment by ypnos-web** [comment]
I can't pinpoint the problem, but as a workaround you should be able to use the loop you had written before to build an array of node **ids** and pass-on that.

**Comment by rgelb** [comment]
Ah, perfect.  That worked.  Thank you!

On Thu, Dec 10, 2015 at 9:17 AM, ypnos-web <notifications@github.com> wrote:

> I can't pinpoint the problem, but as a workaround you should be able to
> use the loop you had written before to build an array of node *ids* and
> pass-on that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jonmiles/bootstrap-treeview/issues/151#issuecomment-163691851>
> .
>



-- 

Regards,
Robert

**Comment by jonmiles** [comment]
@rgelb the methods that accept multiple nodes in array, expect a flat array and not the nested array structure that is input and returned from the node.nodes.  I expect this was your problem, although if you encountered any specific errors it would be worth sharing them.

In terms of performance, version 1.x has significant issue here.  I have done a major rewrite recently to significantly increase rendering related performance and this will be available as part of 2.0; expected soon.  You can check it out by pulling the `develop` branch.  

Likewise if you want to help improve the documentation, such as the usage of arrays in these methods please do so on the `develop` branch.

**Comment by suoutsky** [comment]
so, what  can  i do

**Comment by feiyuw** [comment]
+1
I met this issue too.
