### ISSUE TITLE
Is it just me or develop branch isn't working?

### ISSUE THREAD

**Issue by khajvahmac** [jonmiles/bootstrap-treeview#159]
I have implemented `addNode`, `addNodes` and `removeNode` which works on master branch however. I tried to implement it for develop branch but most of the stuff is broken. How would you like me to test and submit a pull request?

**Comment by hgillh** [comment]
Hi khajvahmac,

Can you please help me in implementing addNodes in my project.
I need it urgently. Please give me an example of how you use it.
Thanks in advance

**Comment by khajvahmac** [comment]
@hgillh 
[bootstrap-treeview.js.zip](https://github.com/jonmiles/bootstrap-treeview/files/244882/bootstrap-treeview.js.zip)
I have attached ziped js file with addNode(s)

**Comment by hgillh** [comment]
Hi @khajvahmac 

Thank for so much for help

**Comment by hgillh** [comment]
I am trying to add an array of nodes on expand event. But it is not adding the nodes.
I am calling addNodes method in following manner. 
$('#tree').treeview('addNodes', [{ text: 'xyz', catid:20, nodes:[]}],1);

Please guide me if I am doing anything wrong.

**Comment by jonmiles** [comment]
It may not work as `develop` is a complete rewrite of DOM rendering.

**Comment by khajvahmac** [comment]
@jonmiles very good. I didn't like the old version either.
