### ISSUE TITLE
linkenabled doesnt work

### ISSUE THREAD

**Issue by jsgspotifi** [jonmiles/bootstrap-treeview#160]
Somebody help me, the enableLinks=true is not working
![2015-12-26_010457](https://cloud.githubusercontent.com/assets/15272468/12003880/b73b14fe-ab6c-11e5-9b06-ba889ea64f22.png)

**Comment by jsgspotifi** [comment]
enableLinks rather, doesnt work. HELP :((

**Comment by jsgspotifi** [comment]
![2015-12-26_020800](https://cloud.githubusercontent.com/assets/15272468/12004053/82efc5d8-ab75-11e5-98d0-9e7d0fa27104.png)

**Comment by jonmiles** [comment]
There's a working example on the online demo - jonmiles.github.io/bootstrap-treeview/.  The demo source is also included in the project.

**Comment by jonmiles** [comment]
Hyperlink support will be removed (#219) in up coming release

**Comment by plonko** [comment]
Hey, thanks for the library, it's very useful! 
Just wonderin - why are you removing href support? thanks
