### ISSUE TITLE
no demo in downloads npm link broken why bother?

### ISSUE THREAD

**Issue by michaeljcoyne** [jonmiles/bootstrap-treeview#162]
no demo in downloads npm link broken why bother?

**Comment by jonmiles** [comment]
There is a demo in the download if you build and rub the project.  The link from GitHub to online demo also works!

**Comment by michaeljcoyne** [comment]
usually demos work outside the box - you haven't included the dependencies. Cant find the link on here for demo - shame because it looks good. If only I could see a working example!

**Comment by jonmiles** [comment]
You do not commit dependencies to source code, this would substantially increase the size of the package and are not required for use in production.

The online demo link is http://jonmiles.github.io/bootstrap-treeview.

**Comment by michaeljcoyne** [comment]
I thought it was a sortable one - thanks anyway.
