### ISSUE TITLE
use url for get date!

### ISSUE THREAD

**Issue by nanzexu** [jonmiles/bootstrap-treeview#164]
insert code in _init: function
<code>
_init: function(options) {

			if(options.url){
                $.ajax({
                    url:options.url,
                    type:'post',
                    async : false,
                    success:function(res){
                        options.data=res;

                    }
                });
			}

</code>

demo:

$("#treeview").treeview({url:url,showTags:true});

**Comment by jonmiles** [comment]
Non-sense
