### ISSUE TITLE
adding ajax response

### ISSUE THREAD

**Issue by trondhuso** [jonmiles/bootstrap-treeview#165]
Hi,
First: Thanks for a fantastic tree view code. I have sort of implemented it - as in a mockup it works nicely, but when I try and add nodes dynamically I am getting some problems.
Here is my ajax:
    var internationalCountriesUrl = "http://example.com/Api/Country/GetAllCountries";

            var response = $.ajax({
                url: internationalCountriesUrl,
                dataType: 'json',
                async:false
            }).done(function (data)
            {
                return data;
            }).responseJSON;

the output is like this:
     [

       {

    "text": "AFC",

    "href": "82",

    "state": {

      "checked": false,

      "disabled": false,

      "expanded": false,

      "selected": false

       }

     },

     {

    "text": "Albania",

    "href": "25",

    "state": {

      "checked": false,

      "disabled": false,

      "expanded": false,

      "selected": false

    }

      }
    ]

I am trying to implement it like this:
     var data = [
                {
                    text: "Sport",
                    state: {
                        expanded: true
                    },
                    nodes: [
                        {
                            text: "Soccer",
                            state: {
                                expanded: true
                            },

                            nodes: [
                                {
                                    text: "Foo Soccer",
                                    state: {
                                        expanded: true
                                    },
                                    nodes: [
                                        {
                                            text: "Local Soccer Men",
                                            state: {
                                                expanded: true
                                            }
                                        },
                                        {
                                            text: "1. Soccer men"
                                        }
                                    ]
                                },
                                {
                                    text: "Internasjonal Soccer",
                                    nodes: response
                                }
                            ]
                        }
                    ]
                }
            ];
            return data;

What ever I do, I am getting errors in the console.
The code above returns:
TypeError: invalid 'in' operand obj

If I add [] around response in the json-structure, I am getting:
TypeError: b.state is undefined

Any help welcomed :)

Trond

**Comment by jonmiles** [comment]
Sorry it's not possible to answer your question based in the information provided. It's also an implementation issue and not related to the bootstrap-treeview.
