### ISSUE TITLE
Use bootstrap thumbnail preview for icons?

### ISSUE THREAD

**Issue by Luttenegger** [jonmiles/bootstrap-treeview#166]
Is there a possible way to add the thumbnail preview feature that [Lightbox](http://ashleydw.github.io/lightbox/) offers to branches that have icons? So when the icon is clicked, it opens up a preview from the image folder?

Edit: An example of the html that would be appended:
```
<a href="img/images/Tesla.jpg" data-toggle="lightbox" data-gallery="gallerymode" data-title="Tesla (Red)" data-parrent="">
<img class="img-responsive" src="img/images/Tesla.jpg" style="width:190px;" alt="Tesla Vehicle">
</a>
```

**Comment by jonmiles** [comment]
Not a valid question, out of scope.
