### ISSUE TITLE
attempting to do a client-side install downloads too much, including phantomjs

### ISSUE THREAD

**Issue by kasajian** [jonmiles/bootstrap-treeview#170]
I'm trying to do a client-side install to use the package, not build it:

npm install bootstrap-treeview --save

but in the process, it seems to be doing way too much.  It's downloading phantomjs, and failing because I don't have bower installed.

Would it be possible to have
npm install bootstra-treeview
only download the components that are necessary to use the software, and not download dev dependencies?

**Comment by mjohnsonengr** [comment]
+1
sure it's fine if I install bower with `npm install -g bower` but I'd rather not.

**Comment by jonmiles** [comment]
Related to #196

**Comment by jonmiles** [comment]
Done, bower has been removed from the build process and is no longer a dependency.

**Comment by kasajian** [comment]
Out of curiosity, why is phantomjs a "dependency" rather than a "devdependency" ?
