### ISSUE TITLE
Click on the node, not only the text, to activate link

### ISSUE THREAD

**Issue by inbal-greenwald** [jonmiles/bootstrap-treeview#172]
Hello, 
Is there a way to do the link, by pressing the entire node/child node?
Thank you,
Inbal

**Comment by inbal-greenwald** [comment]
Got it. Thanks.

**Comment by inbal-greenwald** [comment]
onNodeSelected: function (event, data) {
                            Cookies.set('selectedTreeNode', data["nodeId"]);
                            $(this).treeview('toggleNodeExpanded', data.nodeId);
                            if (data.href != undefined) {
                                window.location.href = data.href;
                            }
                        }

 $('#treeview').on('nodeUnselected', function (event, data) {
                        $(this).treeview('toggleNodeExpanded', data.nodeId);
                    });

**Comment by dylanh724** [comment]
Thanks for sharing - strange this isn't an option - it's super awkward when the entire node isn't a link (select/deselect events are awkward)
