### ISSUE TITLE
getSelected() buggy when links are enabled .. how to make link cover entire node instead of just text?

### ISSUE THREAD

**Issue by dylanh724** [jonmiles/bootstrap-treeview#177]
When you click a link, it will enable selection.
When you click a link, it will disable selection.
However, when you click the OUTSIDE of a link (doesn't trigger link), then click the middle text (triggers link), it deselects.

From a programmers perspective, it's working as intended.

But from a users perspective, he's wondering "if this [node] was highlighted, and I clicked on it, why did nothing happen?"

That said ... how can I make the entire node activate a href link, instead of JUST the middle text? This will make things way less awkward

**Comment by dylanh724** [comment]
Workaround is here:
https://github.com/jonmiles/bootstrap-treeview/issues/172

But not a solution ;) if this is untouched after I'm done with my project, I'll poke around a bit

**Comment by jonmiles** [comment]
Hyperlink support will be removed (#219), please use custom events instead
