### ISSUE TITLE
Question - Anyone has a code example with a MVC implementation? Controller and a view?

### ISSUE THREAD

**Issue by aleksnadar5** [jonmiles/bootstrap-treeview#180]
Hi, 

Does anyone has a code example with a MVC implementation? Controller and a view?

Thank you

**Comment by mxmissile** [comment]
What language and framework? There are literally hundreds of Model View
Controller frameworks out there.

**Comment by aleksnadar5** [comment]
Sorry, should have specified C# and MVC 5. 

Thank you
