### ISSUE TITLE
Improve search speed

### ISSUE THREAD

**Issue by aflar** [jonmiles/bootstrap-treeview#188]
Hi,
I'm using treeview and trying to search items in it. Right now  tree contains 1283 items. When I'm trying to enter more than 3 letters for product name, tree behaviour becomes very sluggish, and  'un-usable'. I think that more than speed itself, the issue is that the search is not asynchronous, hence it feel like it freezes, and it doesn't respond to further key inputs.

Here is the example of search function (tree contains several nodes, so it works well, but if you will increase tree up to 1000 items, then search starting working really slow): https://jsfiddle.net/0hLu1cu6/13/

**Comment by davidgarcia88** [comment]
I experienced this same issue. Any pointer on a fix or where in the code we should look to consider coding a solution would be appreciated.

**Comment by jonmiles** [comment]
I believe this is related to #76, you can test it on develop (I was previously looking for testers)
