### ISSUE TITLE
缺乏自定义字段作为text

### ISSUE THREAD

**Issue by yangdan8** [jonmiles/bootstrap-treeview#190]
缺乏自定义字段作为text

**Comment by yangdan8** [comment]
缺乏自定义字段作为text

**Comment by AdamHess** [comment]
For those of you who don't read Chinese: 

"Lack of Custom Fields as Text"

**Comment by lawtatfaitony** [comment]
"Lack of Custom Fields as Text"
how to settle this question?

**Comment by jonmiles** [comment]
Not enough information
