### ISSUE TITLE
How to achieve Click to another iframe

### ISSUE THREAD

**Issue by kennedyzt** [jonmiles/bootstrap-treeview#191]
How to achieve Click to another iframe

**Comment by kennedyzt** [comment]
like target

**Comment by jonmiles** [comment]
You would be better off using a custom event like nodeSelected and then updating any external dependencies.

**Comment by 3xxx** [comment]
`<div class="col-lg-9">
        <iframe src="/secofficeshow" name='main' id="iframepage" frameborder="0" width="100%" scrolling="no" marginheight="0" marginwidth="0" onLoad="iFrameHeight()"></iframe>
</div>`
`$('#treeview').treeview({
          data: json,
          enableLinks:true,
          showTags:true,
        });
        $('#treeview').on('nodeSelected', function(event, data) {
          alert("Hello World!");
          document.getElementById("iframepage").src="http://www.baidu.com";
        });`
