### ISSUE TITLE
checkNode method problem

### ISSUE THREAD

**Issue by rishisahi** [jonmiles/bootstrap-treeview#194]
Hi,

I am trying to check specific node which has custom id "M-CSP-HID-1301-009V" defined in the tree with id attribute. So When I try following code my tree crashes and says 
**TypeError: node.state is undefined**
` $('#related-hazard-display').treeview('checkNode', "M-CSP-HID-1301-009V", { silent: true });`

here is my jsfiddle,
https://jsfiddle.net/0hLu1cu6/16/

Basically I am expecting following line to work in the code and select the node which has given id,
`$('#treeview-searchable').treeview('checkNode', 'M-AMA-HID-1301-009R' );`

**Comment by jonmiles** [comment]
Sorry but this is a know problem in current release, #103 will be implemented in the near future to resolve this issue.
