### ISSUE TITLE
Tags disappear on selected node

### ISSUE THREAD

**Issue by dotnetmat90** [jonmiles/bootstrap-treeview#195]
Hi guys!

I have edited a little bit library, so I could find tag elementById and update 'tag' value. However after I click on node the values are cleared. How can I fix this? 

`	// Add tags as badges
			if (_this.options.showTags && node.tags) {
				$.each(node.tags, function addTag(id, tag) {
					treeItem
						.append($(_this.template.badge)
							.append(tag).attr('id', "eso_" + node.nodeId)
						);
				});
			}`

Or how can I achive this behaviour?

**Comment by zikidevelop** [comment]
Hi dotnetmat90,
 
I had also the same problem, it seems that the event select is clearing the info and printing the original info, the info sent during the load of the page.

I tried different solutions but finally what I did successfully is to set all the times the tag value:

if (_this.options.showTags && node.tags) {                            
				$.each(node.tags, function addTag(id, tag) {

                                **tag = myObjectCounter[node.href]**

                                 treeItem
						.append($(_this.template.badge)
							.append(tag)
						);
				});
			}       

I have an object in where I update every event the number to be shown in every node as a badget, so I set in every select and deselect, and everything looks right now.

Yours,

ZD

**Comment by jonmiles** [comment]
The tree is re-render the correct information, it can not handle external changes.
