### ISSUE TITLE
package.json does not include bower as a depency, but it's required to build

### ISSUE THREAD

**Issue by evol262** [jonmiles/bootstrap-treeview#196]
Trying to npm install patternfly (which includes bootstrap-treeview) or bootstrap-treeview fails, since bower is not present, but it's required to install bootstrap-treeview:

sh: bower: command not found
npm ERR! Linux 4.4.2-301.fc23.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! bootstrap-treeview@1.2.0 install: `bower install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the bootstrap-treeview@1.2.0 install script 'bower install'.
npm ERR! This is most likely a problem with the bootstrap-treeview package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bootstrap-treeview
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls bootstrap-treeview
npm ERR! There is likely additional logging output above.

**Comment by haoziluo** [comment]
+1

**Comment by chlab** [comment]
I also had this problem.

For now I did

    npm install --save-dev bower
    npm install --save bootstrap-treeview

But the dev-dep should definitely be in bootstrap-treeview.

**Comment by jeff-phillips-18** [comment]
Is there a reason that bower install is done as part of the npm install?

Can https://github.com/jonmiles/bootstrap-treeview/blob/master/package.json#L27 be removed so that the npm install does not require bower?

**Comment by jonmiles** [comment]
Bower has now been removed from the build process, as of v2.0.
