### ISSUE TITLE
Misalignment of over grown tree node

### ISSUE THREAD

**Issue by orakle** [jonmiles/bootstrap-treeview#20]
first of all, thank you very much for this simple and superb control. I am using this on projects for the past few months and purely impressed by the simplicity, recently I am running in to an issue where I see misalignment of text when the text of a node doesn't fit in a single line. Screenshot as below.

![bst over grown](https://cloud.githubusercontent.com/assets/2844591/3943756/c4781d32-25c7-11e4-9445-bd27bcc6ecd0.png)

Thank You

Miki Oracle

**Comment by jonmiles** [comment]
Thanks for your comments.

I'm really not sure what I can do about this as it's designed to leverage bootstraps list view, which also works this way.  The only thing I can suggest is to override the css in your project.
