### ISSUE TITLE
Reload entire tree at expand-collapse events

### ISSUE THREAD

**Issue by prasadKodeInCloud** [jonmiles/bootstrap-treeview#200]
Hi,

I noticed that the entire tree view is re-created at node expand-collapse events. Is there anyway to prevent this performance issue by setting the visibility of nodes as per this example? https://jsfiddle.net/jhfrench/GpdgF/

**Comment by jonmiles** [comment]
This is covered by #76 which is currently available to test on develop and will be part of 2.0 release when I get time finish if off.
