### ISSUE TITLE
Support custom node identifier please

### ISSUE THREAD

**Issue by yaohuah** [jonmiles/bootstrap-treeview#202]
First off, this is a truely nice plugin, thanks for the good work.
Say I have a tree in place, and then I want to use javascript to dynamically set specific nodes to 'checked' status.
I understand that we can feed the tree json with 'state:checked' nodes, but in some circumstances we just have to do it using javascript.

Normally I would use method like this: 
```javascript
$('#tree').treeview('checkNode', nodeId);
```

The problem is that I don't know the internal (incremental) nodeId for some specific node in advance.
It would be nice if I can manually set the nodeId for each node, maybe like this:
```javascript
 function getTree(){
    var data = [
    {"nodeid":12,"text":"stock","nodes":[
        {"nodeid":13,"text":"strategy","href":"#"},
        {"nodeid":14,"text":"BasicAnalysis","href":"#"}]
    ,"href":"#"}];
    return data;
 }

$('#tree').treeview({
    data:getTree(),
    showCheckbox:true,
});

$('#tree').treeview('checkNode',14);  
```

**Comment by jonmiles** [comment]
Thanks, this is covered by #103
