### ISSUE TITLE
How can i use bootstrap-treeview with Bootstrap 4, seems i cannot expand tree nodes,

### ISSUE THREAD

**Issue by oraclub** [jonmiles/bootstrap-treeview#206]
i'm trying to use bootstrap-treeview with Bootstrap 4, but seems i cannot expand tree nodes,
any workaround?

Thanks & Regards,
Martin.

**Comment by jonmiles** [comment]
If bootstrap v4 is every finished, which right I doubt will happen.  Then I will look to add support.
