### ISSUE TITLE
Populate treeview with MySQL db

### ISSUE THREAD

**Issue by perlfan2009** [jonmiles/bootstrap-treeview#209]
Hi there - is it possible to populate the treeview with SQL? Is there an example somewhere? Thanks for help. FRANK

**Comment by seanlindo** [comment]
This is a client-side element. Doesn't it make sense to write an API to retrieve your data and transform it sever-side or client-side into a format that's suitable for this plugin?

**Comment by jonmiles** [comment]
As per @seanlindo statement, this makes no sense and will not be considered
