### ISSUE TITLE
Checkable Tree  can not use;stupid

### ISSUE THREAD

**Issue by mmm8955405** [jonmiles/bootstrap-treeview#221]
First of all, you have a good writing style, but gets all the select drop down menu, do very very stupid. Front page doesn't know what back-end needs. All in all. I'm looking at this for a few days, just doesn't work. Are garbage

**Comment by jonmiles** [comment]
If you can't use it then yes I guess you must be stupid.  I suppose English is stupid too right!

Thanks for your contribution, really helpful.
