### ISSUE TITLE
Which branch should I use?

### ISSUE THREAD

**Issue by istrau3** [jonmiles/bootstrap-treeview#222]
Looks like the last commit in master is a year ago while develop branch is being regularly updated. Should I use the develop branch? Is this project still being maintained for public consumption (was it ever?)

Thanks.

**Comment by jonmiles** [comment]
The project follows GitFlow (https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)

**Comment by istrau3** [comment]
@jonmiles Just a little worrisome that the last commit in the master branch is over a year ago. Why is that? Sorry for all the questions, just weighing this project against jqTree. I need to work one of them into an aurelia application that will go to production soon and I don't want to be stuck with a dependency that is not being maintained.

**Comment by jonmiles** [comment]
This is a project I developed in my spare time and subsequently open sourced for others to use.  I'm not offering a product, service or warranty either expressed or implied.  If I have time and I can be bothered I work on it from time to time.  I'm currently working towards a v2.0 rewrite and hope to complete this in the following week or so but again I make no guarantees.

**Comment by istrau3** [comment]
@jonmiles Ok, thanks.
