### ISSUE TITLE
package.json main is incorrect 

### ISSUE THREAD

**Issue by istrau3** [jonmiles/bootstrap-treeview#223]
Failing in npm3. Should just be a string. No need to include the css file in there I think. Also, it shouldn't be a minified file (so that those using bundlers can produce sourcemaps mapping to the preminified source). Should probably just read:

```
"main": "src/bootstrap-treeview.js"
```

**Comment by jonmiles** [comment]
Thanks.  Actually I'm aware of this already and plan to address it in the next release.
