### ISSUE TITLE
how to get checked nodes?

### ISSUE THREAD

**Issue by DollBin** [jonmiles/bootstrap-treeview#231]
how to get checked nodes?

**Comment by DollBin** [comment]
var node,
            nodeId = 0,
            checkedNodes = [];

        do {

            node = tree.treeview("getNode", nodeId);

            if (node && node.state.checked) {
                checkedNodes.push(node);
            }

            nodeId++;

        } while (node.nodeId != undefined);

        return checkedNodes;

**Comment by jonmiles** [comment]
There's a getCheckedNodes method if you look at the Api exposed. It's currently undocumented, there's a issue to update the doc.

**Comment by torjuss** [comment]
First of all: Thanks for a great framework! 
I had a look at /src/js/bootstrap-treeview.js and noticed that the only methods that lacks documentation is getChecked and getUnchecked. Would be nice if you could add those to the readme as well.
