### ISSUE TITLE
i want to put parent in <div>  and child in another <div>  --> because when i click on parent div hide and child div show

### ISSUE THREAD

**Issue by afnanmezied** [jonmiles/bootstrap-treeview#232]

**Comment by jonmiles** [comment]
I don't understand but I suspect what you're asking for is not possible.  If it is it will be documented in the README.

**Comment by afnanmezied** [comment]
i have 2 tab the first tab like this

(tab 1 )

- parent 1
- parent 2
- parent 2

when i click on parent 1 open new tab and appear like this 

(tab 2)

child 1.1
child 1.2
child 1.3
child 1.4

or when click on parent 2 open new tab and appear like this

(tab 2)

child 2.1
child 2.2
child 2.3
child 2.4

so i don't want parent and child appear in the same tab :) 

@jonmiles :)

**Comment by jonmiles** [comment]
Well good luck with that, it doesn't sound like a tree to me and it's certainly not possible with this component.
