### ISSUE TITLE
When I use method getParent to root or nodes with no parent , it can not return undefined, is this a bug?

### ISSUE THREAD

**Issue by Dream-idai** [jonmiles/bootstrap-treeview#233]

**Comment by DollBin** [comment]
you can test state property of result

**Comment by jonmiles** [comment]
Yes this is a bug, it has been fixed in v2.0 which I hope to finish and release soon.  If you like to test the latest pre-release you can use 'develop' branch.  Please note there are breaking changes, as yet undocumented, review README for changes.
