### ISSUE TITLE
expose findNodes in API

### ISSUE THREAD

**Issue by coclav** [jonmiles/bootstrap-treeview#234]
I wanted to "reveal" some of my nodes based on a few criteria in the nodes, I am writting my own function but reading the code I realised this is exactly what "findNodes" does.

Maybe this function could be exposed in the public API ?

**Comment by jonmiles** [comment]
This has been addressed in the v2.0 which is currently in development; see branch `develop`.  Sorry but I don't have the bandwidth to retro fit to current version.
