### ISSUE TITLE
Child nodes with different names

### ISSUE THREAD

**Issue by rafakwolf** [jonmiles/bootstrap-treeview#235]
i have data with many child nodes, but the names is not only "nodes".

 like this:

`var tree = [
  {
    text: "Parent 1",
    nodes: [
      {
        text: "Child 1",
        theOtherNodes: [
          {
            text: "Grandchild 1"
          },
          {
            text: "Grandchild 2"
          }
        ]
      },
      {
        text: "Child 2"
      }
    ]
  },
  {
    text: "Parent 2"
  },
  {
    text: "Parent 3"
  },
  {
    text: "Parent 4"
  },
  {
    text: "Parent 5"
  }
];`

Thanks

**Comment by jonmiles** [comment]
It won't work, is not supported, will not be supported. Change your names.
