### ISSUE TITLE
Add filter event to process data before rendering

### ISSUE THREAD

**Issue by McNetic** [jonmiles/bootstrap-treeview#236]
Sometimes, you don't have control of the data source for the treeview, and/or want to adjust the data for the nodes on the client side (for example, to have the data api returning pure data and add the node display options from javascript). It would therefore be helpful to be able to specify an event handler/filter function to process the data before rendering the treeview.

If you agree, I could implement a proposal, if you are interested.

(this feature would also provide a possible solution to #235)

**Comment by jonmiles** [comment]
I don't see why this is needed.  It can be done at the moment with the following steps.

Steps
1. Query your data source, pull from server e.g. Ajax
2. Manipulate the data array
3. Initialize tree with cleansed data

So why would need an event handler / filter ?

**Comment by McNetic** [comment]
It's a convenience method, of course. Strictly speaking, the dataUrl parameter is also not needed...

**Comment by DollBin** [comment]
It's no need
