### ISSUE TITLE
implement addNode,removeNode,editNode

### ISSUE THREAD

**Issue by DollBin** [jonmiles/bootstrap-treeview#237]
The three methods should have as follow:

addNaode(parentId,node)

removeNode(nodeId)

editNode(nodeId,node);

**Comment by jonmiles** [comment]
Covered by #50, almost complete.  Pending v2.0 release, develop branch if you want to test.

Please take the time to review existing issue before raising new ones.  This save me time, time that I can spend on development instead of answering questions.

**Comment by wwk3j** [comment]
Hi, is the branch you are working on accessible? I would like to test the functionality to add/remove. Thanks.

**Comment by jonmiles** [comment]
Yes, it will be the only unmerged feature branch.  I think it's finished, just needs a once over and a tidy up.  Been on holiday, now busy.

**Comment by LrdArc** [comment]
There seems to be a bug regarding addNode function. It doesn't added new node into parent node. This is my code:
`			$( '#sidebar' ).on( 'nodeExpanded', '#browse-file', function( event, node ) {
				console.log( JSON.stringify( node ) );
				$( '#browse-file' ).treeview( 'addNode', [ { text: 'new node', nodes: [ { text: 'test' } ] }, node, false, { silent: true } ] );
				console.log( JSON.stringify( node ) );
			} );
`

Or perhaps am I doing it wrong?

This is the node's object before the function executed: (it may help for debug)
[http://pastebin.com/AAwHzRKA](url)

After the function executed:
[http://pastebin.com/SgYRMbqp](url)

**Comment by evijayan2** [comment]
I used the above code, i get the below error message
bootstrap-treeview.min.js:1 Uncaught TypeError: Cannot read property 'visible' of undefined
