### ISSUE TITLE
How to rename nodes in version 1.2.0

### ISSUE THREAD

**Issue by mykeblack** [jonmiles/bootstrap-treeview#241]
Hi,
I'm building an application using the current version 1.2.0 release and need to be able to change the text on the selected node in response to an external event (in this case only one node is ever selected). How can this be done? I've tried updating the element using $(".node-selected").text() but it reverts back when you close and reopen the parent.

I see that in version 2 there is an 'updateNode' method but when I tried out version 2 it didnt allow me to open and close folders (using latest version of chrome desktop browser) so cannot be considered for use yet, hence I need to get a quick fix for version 1.2

thanks.

myke.

**Comment by jonmiles** [comment]
The only way in v1.2.0 is by rebuilding the entire treeview via reinitialisation.  That's was one of the main objectives of the v2.0 re-design.

Please could you expand on what you mean by "version 2 it didnt allow me to open and close folders"?  I'm developing and testing regularly with Chrome and not experiencing any issues.

**Comment by mykeblack** [comment]
Thanks for the info Jon. I finally got version 2 working on my test site- turns out there was an error in my edited CSS file, so the browser was not loading all of the bootstrap-treeview.css file. This meant that the open and close events did not appear to fire but there were no error messages showing in the console window. A cautionary tale for others I think.

Thanks for the great work, I'll see if I can get the update node method working now.

**Comment by mykeblack** [comment]
Hi, I have tried to use the following code in version 2.0 to update the text on the selected node: 

`$(document).on("click", "#btnSave", function () {
	// javascript here to update node with new name if appropriate...
	SelectedNodes = $('#tree').treeview('getSelected'); // only one node can be selected
	console.info(SelectedNodes);
	if (SelectedNodes.length > 0) {
		node1 = SelectedNodes[0];
		console.log("old node:")
		console.info(node1);
		var replacedNode = {};
		// copy properties across, will have to do extra work if node has children but will cross that bridge later...
		for (var k in node1) replacedNode[k] = node1[k];
		replacedNode.text = "NEW TEXT";
		replacedNode.folderTitle = "NEW TITLE";
		console.log("replaced node:");
		console.info(replacedNode);
		$('#tree').treeview('updateNode', [node1, replacedNode, { silent: true }]);
	} else {
		console.log("no node selected");
	}
})`


When I call updatenode, the selected node disappears from the tree altogether

This is a bit of a long way around doing it, it would be easier if there was a 'renameNode' method which just replaces the text.

thanks.

Myke.

**Comment by jonmiles** [comment]
Hey Myke

Is it actually causing you a problem and does it matter that the node is replaced?

FYI I'm replacing the node this way in order to update all node properties and not just the node text value.  It seemed the simplest way would be to replace the node in the collection, remove the old DOM element and then have the tree re-render the missing node.  This should handle all current and future rendering options, as well as recursively handling any children.  In theory this should be transparent to the user.

Thanks for the feedback, I will it some thought.

**Comment by mykeblack** [comment]
Hi,
Thanks for the reply. I'm now using the following code to replace the text in the DOM directly. this seems to be working for now:

    $(".node-selected").contents().filter(function () {return this.nodeType == 3;}).replaceWith("new title");

I think there was something in my ajax callbacks that was causing an issue with the dom replacement, but I've now fixed that.

thanks.

**Comment by ms502040** [comment]
Hi,
i have same issue with node disappear from tree. You just need remove line 1233 in file bootstrap-treeview.js ( this._removeNodeEl(node) )
`	Tree.prototype.updateNode = function (node, newNode, options) {
		if (node instanceof Array) {
			node = node[0];
		}

		options = $.extend({}, _default.options, options);

		// insert new node
		var targetNodes;
		var parentNode = this._nodes[node.parentId];
		if (parentNode) {
			targetNodes = parentNode.nodes;
		} else {
			targetNodes = this._tree;
		}
		targetNodes.splice(node.index, 1, newNode);

		// remove old node from DOM
//		this._removeNodeEl(node);   <<---------------------

		// initialize new state and render changes
		this._setInitialStates({nodes: this._tree}, 0)
		.done(this._render.bind(this));
	};`
