### ISSUE TITLE
treeview not created sometimes if reload too fast

### ISSUE THREAD

**Issue by piekatoski** [jonmiles/bootstrap-treeview#260]
Hello.

I'm having problems if reload my page too many times. If I do that, in some cases, I got the error:

Not initialized, can not call method : search

well, I guess if I could know when the treeview is ready, it couldn't happen.
There is a way for me to know when it's ready, so I can call anything?

**Comment by jkshay** [comment]
`$(document).ready(function(){
    // Do your treeview manipulation here.
})`

**Comment by piekatoski** [comment]
I thought about that, but not implemented. My mistake. Thanks.
