### ISSUE TITLE
Updates to develop branch

### ISSUE THREAD

**Issue by priley86** [jonmiles/bootstrap-treeview#267]
Hi, is there any chance we can merge these PRs to develop branch soon? 
https://github.com/jonmiles/bootstrap-treeview/pulls/skateman

We have multiple parties downstream from our [patternfly](https://github.com/patternfly/patternfly) project interested in these changes and would like to update our dependency to target `develop` until they can be merged to `master`. These PRs fix a security alert and make other customizations to the treeview we'd find useful.

**Comment by jonmiles** [comment]
It's doubtful that any current PRs will be merged, unless they were written against develop they will no longer to valid.

I will not be merging changes just because people create PRs. 

I will finish v2.0 as and when I have time. Paid client works first, social life then open source.

**Comment by priley86** [comment]
@jonmiles thanks for your response - these PRs are written against `develop` branch. Do you see a lot of changes coming to `develop` branch soon? We would like to incorporate these changes, but if you don't think you will have time, let us know.
