### ISSUE TITLE
onhoverColor seems doesn't work 

### ISSUE THREAD

**Issue by junneyang** [jonmiles/bootstrap-treeview#34]
i use bootstrap-3.3.1 jquery-1.11.2

specifically setting as follwed: 

$('#tree').treeview({
			data:tree,
			collapseIcon:"glyphicon glyphicon-minus-sign",
			emptyIcon:"glyphicon glyphicon-minus-sign hidden",
			enableLinks:true,
			expandIcon:"glyphicon glyphicon-plus-sign",
			highlightSelected:true,
			onhoverColor:"#D3D7CF",
			levels:2,
			selectedColor:"#FFFFFF",
			selectedBackColor:"#D3D7CF",
			nodeIcon:"hidden",
			showBorder:false,
			showTags:true
});
but onhoverColor seems doesn't work 

i am looking forward to your help very much, thank you !

**Comment by jonmiles** [comment]
It works fine for me, the tests pass and if you look in the project under /public you will find index.html that show it working on one of the examples; I think it's titled 'A splash of colour'.

I have also test it with the options you provided in your example, against bootstrap 3.3.2 and jQuery 1.11.2 and again it works.
