### ISSUE TITLE
Populate on demand and tooltip

### ISSUE THREAD

**Issue by Muhanady** [jonmiles/bootstrap-treeview#35]
Y you do not add populate on demand to the tree, if its set to True make the plus sign visible.

and tooltip is needed too

**Comment by jonmiles** [comment]
I'm not sure what you are asking?

**Comment by waldnercharles** [comment]
I believe he is asking for lazy loading support or maybe for an example of how lazy loading might be done? Although, I believe this is outside the scope of bootstrap-treeview and should fall on the user.

**Comment by jonmiles** [comment]
Thanks @waldnercharles, I've raised #44 for future consideration.
