### ISSUE TITLE
Support remote data requests

### ISSUE THREAD

**Issue by jonmiles** [jonmiles/bootstrap-treeview#39]
Support loading of remote data from a given URL, via an ajax request.

**Comment by jonmiles** [comment]
To support extremely large tree structures, consider supporting remote data at any given node level, requested and loaded on demand.

**Comment by mewsoft** [comment]
First, this is a great plugin for bootstrap.
Second it is a must feature to add dynamic nodes loading, I am trying to use this one as an alternative for http://www.jstree.com/ which is fantastic also and a complete product but this one looks better choice for bootstrap as a menu tree not just regular tree.

As an enhancement for this menu tree or tree menu, I'd suggest adding an option for displaying a breadcrumb at the top on the tree itself builtin so user knows his current sub tree selections.

**Comment by HeikoKanzlerNektan** [comment]
+1

**Comment by generalthink** [comment]
hello,thanks for you contribution.what version support remote data requests? and is it support asynchronous loading?

**Comment by jonmiles** [comment]
Implemented Ajax based remote loading via dataUrl

**Comment by themescience** [comment]
@jonmiles I just downloaded the latest release, but didn't find the dataUrl functionality.
Nor did I find anything in the demo.
Am I missing something somewhere?
Please and Thanks

By the way, nice job on this!

**Comment by jonmiles** [comment]
I don't think you'll find it in the download, I think that's just releases. It's available in branch develop.

**Comment by wh1pp3rz** [comment]
Is there a way to load data on demand via ajax when a node is first expanded?

**Comment by whanklee** [comment]
Do you tell me when this feature will be available?
