### ISSUE TITLE
Events not unbound when re-initialising tree

### ISSUE THREAD

**Issue by Antaris** [jonmiles/bootstrap-treeview#4]
I'm using the treeview control in a popup dialog representing a gallery selector, the treeview being the basis for the folder listing. Now, upon changing the scope of my dialog, I effectively get a new set of folders, so I need to rebuild the tree. Looking through the source, if I call `.treeview({...})` on a control that has previously been initialised, it chains to `Tree::_init` -> `Tree::_destroy()`. 

The problem I am finding, is I rebind the `onNodeSelected` event when I rebuild the tree, but, the original event function is fired, and then the new event function:

http://jsfiddle.net/ML5WX/1/

It seems the original events are not being removed, so the number of events that get fired per node increases with each rebind.

**Comment by jonmiles** [comment]
Good spot @Antaris, thanks @Feoni4 for sharing!
