### ISSUE TITLE
Would it be OK to add methods for expanding/collapsing the nodes？

### ISSUE THREAD

**Issue by fjmiaoxiao** [jonmiles/bootstrap-treeview#40]
Would it be OK to add methods for expanding/collapsing the nodes？Or if these methods already exsist, it is better to add them to README.md

**Comment by jonmiles** [comment]
No there methods do not exist, the documentation is extensive and covers all available options.

However, #28 has been raised to track these additional methods.  I plan to work on these enhancements in the next month or so but this depends on other work obligations.
