### ISSUE TITLE
demo link?

### ISSUE THREAD

**Issue by Oxicode** [jonmiles/bootstrap-treeview#42]

**Comment by jonmiles** [comment]
The project contains numerous examples but there is currently no demo link.  I will look at adding one in the near future.

If you want to run the examples in the project, and assuming you already have node.js, express.js etc. you can run through the following steps.

* git clone https://github.com/jonmiles/bootstrap-treeview.git
* cd bootstrap-treeview
* npm install
* bower install
* node app.js
* http://localhost:3000
