### ISSUE TITLE
Definable node states

### ISSUE THREAD

**Issue by jonmiles** [jonmiles/bootstrap-treeview#49]
Add node states to the data structure, to add more fine-grained control over a node's initial state.

e.g.
```javascript
states: {
    expanded: true,
    selected: true
}
```

**Comment by stingh711** [comment]
I want to set a leaf node expanded. Should I set all expanded to true along the path or just the leaf node itself?

**Comment by chriskonnertz** [comment]
Seems like you have to expand the whole path.
