### ISSUE TITLE
Add / remove / update nodes programmatically

### ISSUE THREAD

**Issue by jonmiles** [jonmiles/bootstrap-treeview#50]
Add method to support adding and removing nodes programmatically.

Example list of methods, to be confirmed.
* addNode(node, parentId)
* insertNode(node, parentId, index)
* removeNode(id)
* updateNode(id, node)

Once #45 implemented
* removeChecked()

**Comment by HeikoKanzlerNektan** [comment]
I am thinking of using bootstrap-treeview for one of my projects, is there any idea what time this important features might come?

**Comment by jonmiles** [comment]
It's currently assigned to [milestone 1.4.0](https://github.com/jonmiles/bootstrap-treeview/milestones), so approximately May/June this year if all goes well.  I only work on this in my spare time, so it depends how busy I get with other projects.

**Comment by HeikoKanzlerNektan** [comment]
So fingers crossed. I stick with your treeview for now - it's so lightweight and easy to integrate. Hope this feature comes soon. Don't want to change the navigation later. :-)

**Comment by mouse0270** [comment]
This feature would be wonderful! Right now every time a user updates/adds/removes one of their pages, I have to call a server script to generate a new whole new tree. It would be cool to take this load off the server side and place it on the client side. haha.

**Comment by HeikoKanzlerNektan** [comment]
That's exact how I do it at the moment: I track the clicks (open nodes) and whenever I add something to the tree, a reload the tree and open that node. This closes all other open nodes, but at least the current node the user is working on stays open.

**Comment by jonmiles** [comment]
I've moved this feature forward a release, you can now expect it to be delivered in v1.3.0.

**Comment by HeikoKanzlerNektan** [comment]
Great news, Jon.

**Comment by lukin0110** [comment]
Hey Jon. Any idea by when this will be implemented?

**Comment by NightTrain** [comment]
Hey @jonmiles,

First off, awesome implementation

**Comment by NightTrain** [comment]
Hey @jonmiles,

First off, awesome job so far with this project. I've been toying around with it and am trying to find a way to dynamically add a span to the text of a node. For example, when a node is collapsed the text would be "Parent 1..." And when the node is expanded the text would be "Parent 1 <br> has properties x, y, and z". I attempted to do this with the onNodeExpanded and onNodeCollapsed events, but without the ability to re-render the changes wouldn't take affect. 

It looks like "updateNode(id, node)" is exactly what I'm looking for. Any idea when this will be implemented/is there another way to do this currently?

**Comment by perego-pezzetti** [comment]
Hi @jonmiles,
I'm also interested to this. I have to dinamically update node tags of my tree without loosing values (reset tree data) each time I select a tree node. Are there any news on this? Thank you

**Comment by dylanh724** [comment]
Would like to hide or remove

**Comment by AdamHess** [comment]
:+1:  Would love this feature. 

Since you can actually hook additional (non-treeview data) onto the noddes. 

like i want to be able to something like this

```
onNodeSelected: function(event, data) {
     additionalDataOptions = openDialog();
     data["additionalDataOptions"] = additionalDataOptions;     
     return data; 
}
```


Currently, it seems like the easiest solution would be to completely re-render the tree with the data for the node updated.

**Comment by jonmiles** [comment]
Revised proposed methods:

- **addNode(nodes, parentNode, index, options)**
  _- if parentNode false, node will be added to root_
  _- if index false, node will be append to the end of child nodes_

- **addNodeAfter(nodes, node, options)**

- **addNodeBefore(nodes, node, option)**

- **removeNode(node, options)**
  _- will remove node and all children_

- **updateNode(node, newNode, options)**
  _- will replace and all child nodes, unless ignoreChildren passed as true_

**Comment by George35mk** [comment]
jonmiles thnx for your lib, the best documantation ever , the lib is amazing you are the reasson i make ucount on github pls i nead to add node with button because i am noob on programming and i dont have a lot of experience i try to make this but i dont know how :( if you have time can you add this feture, i want to do somthing like this 


$("button").click(function(){

    //and the method to add node inside the tree
  $('#tree').treeview('addNode', parentId);

});

pls can you add this on your code all the lib is perfect only that is missing

**Comment by 3xxx** [comment]
https://github.com/patternfly/patternfly-bootstrap-treeview
