### ISSUE TITLE
Turbolinks enhancement

### ISSUE THREAD

**Issue by bthornto** [jonmiles/bootstrap-treeview#61]
Can you add this, sorry about not doing a pull. Something is horked up locally.  If you have hyperlinks in the tree this will let turbolinks get them rather than a tradional http get.  Avoid the background refresh.

thanks-  treeview is awesome.

```
  $('#tree').treeview({
              enableTLinks: true
```
js:

```
  _template: {
      tlink: '<span></span>'
    }
...

  _clickHandler: function(event) {

      if (!this.options.enableLinks || !this.options.enableTLinks) { event.preventDefault(); }

      var target = $(event.target),
        classList = target.attr('class') ? target.attr('class').split(' ') : [],
        node = this._findNode(target);
...
  else if (self.options.enableTLinks && typeof node.href !== 'undefined') {
          // Add hyperlink
          treeItem
          .append($(self._template.tlink)
            .attr('onclick', 'Turbolinks.visit(\"' + node.href + '\")')
            .append(node.text)
          );
```

**Comment by jonmiles** [comment]
After careful consideration I've decided not to implement this request.  Turbolinks appear on the face of it to be a good idea, that said I think it's very specific to Rails and is probably better handled in one of the event handlers e.g. onNodeSelected.

**Comment by bthornto** [comment]
That's a good idea. Let me see if I can work with that. The above is working well, but I'd rather stay aligned with your code base. 

Thanks
