### ISSUE TITLE
Row Level

### ISSUE THREAD

**Issue by toddaa** [jonmiles/bootstrap-treeview#62]
Is there an easy way to know what level the selected row is?  For example, I need to have top level rows with no children do something different from a row that is a second level underneath one of the top level rows in my custom onNodeSelected function.  I can add a boolean field to the node data that is being loaded, but that seemed like a bit of a hack.

Any advise?

**Comment by jonmiles** [comment]
No level information is recorded against a node, but the node is [designed and documented to be extendible](https://github.com/jonmiles/bootstrap-treeview#extendible).  The best approach is as you suggested, to add additional data values to the node.

**Comment by toddaa** [comment]
Thanks for confirming.  Adding my own as a data value works fine.  I'm never going deeper than 2 so I don't think I will have an trouble doing it this way.

Thanks again!
