### ISSUE TITLE
Is there an "expandToNode" method?

### ISSUE THREAD

**Issue by TrueDub** [jonmiles/bootstrap-treeview#64]
I checked the docs and cannot find a method to allow a user programmatically expand the tree from the root to a specific node (without recursively using the expandNode method).

This would be a handy piece of functionality.

My use case is a search function allows a user to jump to a specific page, and the tree needs to expand to that exact node in the tree also.

**Comment by jonmiles** [comment]
Not currently, I've raised #65.

In the meantime, if you decide to implement yourself the best approach would be to work from your node upwards to the root; using `getParent` and `expandNode` recursively.
