### ISSUE TITLE
Extendible HTML elements

### ISSUE THREAD

**Issue by jonmiles** [jonmiles/bootstrap-treeview#67]
An old pull request #9 no longer merges, originally raised by @smilton.

README.md

```markdown
+## Extendible
 
 You can extend the node object by adding any number of additional key value pairs that you require for your application.  Remember this is the object which will be passed around during selection events.
 
+If you need some key/value pair to be added to node's HTML element, add `data-` prefix to the key:
+
+```javascript
+{
+  text: "file name",
+  'data-path': "path to file"
+}
+```
+
+will render like:
+
+```html
+<li ... data-path="path to file">
+  file name
+</li>
+```
+
```

bootstrap-treeview.js

```javascript
+				// add attrs defined in JSON
+				// but only ones starting with data-
+				$.each(node._data, function(k, v) {
+					if (k.match(/^data\-/))
+						treeItem.attr(k, v);
+				});
```

**Comment by jonmiles** [comment]
After further consideration, I've decided that although this was a good improvement at the time it was originally suggested.  With the new suite of API methods and events it makes more sense to access the data via the node object itself, rather than cluttering the DOM.

**Comment by crickes** [comment]
I found this page as I was looking for exactly this option. I want to combine the treeview with a context menu. The context menu plugin relies on the bootstrap 'data-toggle' attribute being present on the HTML entity, in this case it would be on the <li>. Is there any way to achieve this now?

**Comment by jonmiles** [comment]
For now the best approach would be for you to fork the repository, add your requirements direct to the plugin

**Comment by jamesingham** [comment]
@crickes You should be able to add the data-toggle attribute to all the <li> in the tree like so:
`$("#groups-tree ul").children().attr("data-toggle", "context");`
