### ISSUE TITLE
Status Text

### ISSUE THREAD

**Issue by jperkelens** [jonmiles/bootstrap-treeview#73]
I'd like to be able to place additional text on a node that contains some info about its status (in my case, its the number of child leaf nodes selected). I'm happy to submit a PR for this but wanted to gauge your interest/opinion about implementation.

Since this feature will be fairly use case specific I thought it made sense to pass the treeview a function that accepts a node and returns the additional text. I'm split on whether the function should be passed in as a property on each node, an option on instatiation, or both, in which case node specific functions override the general function. 

For now, I'm working on the "both" case as that's how most features operate, but am happy to switch directions after a discussion. Any thoughts?

**Comment by jonmiles** [comment]
I try not to introduce anything that is too specific, as it becomes a nightmare to manage.  That said it sounds like you might be able to achieve this with existing features, and a few in the immediate pipeline.

If you want to store additional data per node, then is should be stored in the node's data.

if you want to display the additional info as part of the treeview, then you should use tags.  You can add any text you want, and it accepts multiples.

If you want to retrieve the data from the node, nodes are passed around during events, or can be acquired via the API methods e.g. getNode.

I think the final piece which is not quite ready yet, is the ability to update nodes.  This is in the pipe line #50, queued for v1.3.0.  I already know how I'm going to do this, I just need to get around to it.  I might be missing something here but from my interpretation, but I suspect this is probably what your missing.

**Comment by jperkelens** [comment]
Ah missed this comment while I was working on it. Take a look at the PR, and accept or reject it as you see fit. If you decide not to pull it in, I'll use my fork until 1.3.0 comes out and see if I can put together what I need from that.
