### ISSUE TITLE
node on click set focus to top of the list-group

### ISSUE THREAD

**Issue by DemarsM** [jonmiles/bootstrap-treeview#79]
If you use the tree with overflow-y like this:

    .list-group {
      max-height: 400px;
      overflow-y: scroll;
    }

everytime a node is clicked the focus is set to the top of the list-group what is really annoying

**Comment by jonmiles** [comment]
That's because the tree view is rebuilt every time it renders.  That will be address in #76 and #50 expected to be delivered in v1.3.0.

**Comment by DemarsM** [comment]
Very good! Thank you!
