### ISSUE TITLE
How to force indentation width?

### ISSUE THREAD

**Issue by toni-moreno** [jonmiles/bootstrap-treeview#81]
Hi @jonmiles .

I'm trying to force smaller indents by setting in my css

```
.treeview span.indent {
  margin-left: 5px;
  margin-right: 5px;
}
```
but it seems to be hardcoded on the treeview and overwrittes my indentation style

![image](https://cloud.githubusercontent.com/assets/5883405/7548987/ff9f9200-f623-11e4-8822-5034a83ed94a.png)

**Comment by jonmiles** [comment]
Actually this is a known issue, the css in automatically injected when the tree is built.  This was originally a design feature to streamline set-up and allow multiple trees with different styles in the same page.  I'm looking at changing this in v1.3.0, ref #2.

In the meantime you should be able to work around this using option `{ injectStyle: false }`.  Let me know if you do have any other problems.

**Comment by toni-moreno** [comment]
Hi @jonmiles . It is not the best way to fix becaose of lost of all previousy configured styles.


from 

![image](https://cloud.githubusercontent.com/assets/5883405/7559495/ff52a612-f7b7-11e4-9400-200ff64ebc94.png)


to

![image](https://cloud.githubusercontent.com/assets/5883405/7559484/e02693c0-f7b7-11e4-9d0b-a7a05e7109ad.png)

when do you have plans release a new v1.3.0 with a fix for that?

Thank you very much!

**Comment by jonmiles** [comment]
Alternatively, you could make your css selector more specific so that it takes precedence.

```css
.treeview li span.indent {
  margin-left: 5px;
  margin-right: 5px;
}
```

I've just finished and release 1.2.0, so v1.3.0 will be approx 4-6 weeks but depends largely on my work schedule.
