### ISSUE TITLE
Support for real checkboxes instead of icons

### ISSUE THREAD

**Issue by piwnik** [jonmiles/bootstrap-treeview#84]
Hi,

I need support for real checkbox instead of icons. Icons doesn't satisfy me, because I need possibility set 'indeterminate' state. In older version I do that with some hacks (not changeing real library), but now private functions of treeview are hidden, so I have to stay with older version or hack library.

**Comment by jonmiles** [comment]
I'm sorry but adding actual check boxes is not in my vision, or roadmap.  The glyphicons are in-keeping with the fact that it's a bootstrap treeview, they also scale well which you do not get with html check boxes.  

I might add the indeterminate state using glyphicons but that would be as far as I go.
