### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by mxmissile** [jonmiles/bootstrap-treeview#86]
Anyone know who builds the Nuget packages? We are a bit behind I think.

**Comment by jonmiles** [comment]
Not me, until now I didn't even realise it was published to NuGet.

If you take a look [here](http://www.nuget.org/packages/bootstrap-treeview/) it seems to have been published by user bogatykh.

**Comment by mxmissile** [comment]
ahh... I didnt even to think to look there, thanks!
