### ISSUE TITLE
provide Set Id method or provide a mapping of assigned ids to custom ids

### ISSUE THREAD

**Issue by jmoponfire** [jonmiles/bootstrap-treeview#89]
I want to be able to adjust the state of the tree programmatically. I have set my own custom id on all the of the tree nodes when I build it, but I can't seem to access the nodes with those ids. It seems I can only use the assigned ids. But I don't know the ids that are assigned, except by....

I'm in the process of using getNode with nodeId = 0, and loopign through the results to create my own mapping between bootstrap-treeview assigned ids to my ids. Is there an easier way?

**Comment by videni** [comment]
I meet the same problem, it seems  this component is made for show hierarchy data only ,not for  submit data , because usually  when we wanna find submit data to server, we need to find those item being checked, for item being checked, actually , the data suppose to have two properties, such text to display , id to submit.

**Comment by ebengtso** [comment]
Hi, you can set any attributes in the nodes, and get the selected nodes before you submit using => treeview('getSelected'). For example, I'm using the attribute "value" to hold the IDs I submit to the server.

**Comment by mironnn** [comment]
Hi there!
I've got the same problem. I need to assign my custom id for each node and then get them for sending to the server side. 
Ebengtso, could you please advise how did you solve this?
Thank you in advance.

**Comment by ebengtso** [comment]
It's actually very simple

Just add a "value" attribute to each node of the tree, and to this attribute you assign the ID value.

Get all selected nodes using treeview('getSelected'), and read the "value" attribute.

**Comment by webfriend13** [comment]
What If while loading the treeview next-time, I want to select some of the nodes. How can I achieve that feature?

**Comment by ebengtso** [comment]
Just add the attribute state to the nodes that are selected

a_node.state = {selected:true};

**Comment by webfriend13** [comment]
@ebengtso : Thank you for quick reply. But how can I find a node by passing a custom field\property to treeview data source ? My question was more towards finding a node & then assigning set it as selected or checked. Thanks

**Comment by ebengtso** [comment]
here is the code i use, call flagNode with the root node, and value is an array of objects that contains the id

```
flagNode: function(node,value)
	{
			for(var j=0;j<value.length;j++)
			{
				if(value[j].id==node.value)
				{
					node.state = {selected:true};
				}
			}
			if(node.nodes)
			{
				for (var i = 0; i < node.nodes.length; i++)
				{
					this.flagNode(node.nodes[i],value);
				}
			}
	}
```

**Comment by mironnn** [comment]
I always have such error: "Not initialized, can not call method : getChecked". But sometimes getChecked returns not more than one checked node.

My part of code:

    $(document).on('click', '#tree_button', function(event) {
       $.each($('.tree_json').treeview('getChecked'), function(){
           $.get('/nomenklatura/products/'+$(this).attr('value_id_1C')+'/')
       })
    })
1. I have two trees in different divs with  the same class "tree_json");
2. "value_id_1C" - this is my custom id in each node.

I need to get url with my custom id, but getChecked didn't returns nodes.

**Comment by jonmiles** [comment]
@mironnn The error  "Not initialized, can not call method : %" is typically thrown because 1. you have either not initialized the treeview, or 2. the element / selector you are trying to call `.treeview` is incorrect.

**Comment by jonmiles** [comment]
I've read over the your comments and appreciate that there is a short coming here, in that the tool does not provide a direct method to retrieve nodes by any other field than the auto-generated id.  As a consequence I've raised #103 which will be actioned as part of the next release.

However, some of your other comments and approaches seem like you are taking the wrong approach when building your application.  This tool is designed to be a visual plugin, to display data and maintain it's state while it is running.  It's designed to be data driven.  You should be maintaining your data either on the server, or via controllers in a single page app.
