### ISSUE TITLE
How do i collapse all the nodes?

### ISSUE THREAD

**Issue by praveenlobo7** [jonmiles/bootstrap-treeview#90]
How do i collapse all the nodes?

**Comment by jonmiles** [comment]
https://github.com/jonmiles/bootstrap-treeview/blob/master/README.md#collapsealloptions

**Comment by DemarsM** [comment]
Hello :+1:

**Comment by praveenlobo7** [comment]
Tried that, but i got the below error in the console.
"Not initialized, can not call method : collapseAll"

**Comment by jonmiles** [comment]
Either you haven't initialised the tree view, or you're calling the method on the wrong object/element.

Check your code for errors, it does work as all the tests pass and you can see it working on the online demo.

**Comment by praveenlobo7** [comment]
Thank you :)
