### ISSUE TITLE
Update Nuget Version

### ISSUE THREAD

**Issue by Rayj1l** [jonmiles/bootstrap-treeview#92]
Hey, I really like your control.  I downloaded it via nuget package manager in Visual Studio.  The only problem I faced was the version they have is 1.02 and your current version is 1.20.  2 Hours lost trying to figure out why the check boxes didn't work like the version in the demo ;(.

Keep up the great code!
Cheers.

**Comment by mxmissile** [comment]
I have tried to contact the nuget package manager for this but all I get is crickets, probably safe to assume it's dead. I'll see if I can throw up a new package this weekend.

**Comment by mxmissile** [comment]
Message from the author... "Hi Travis! Will update it tomorrow."

**Comment by mxmissile** [comment]
Package has been updated, https://www.nuget.org/packages/bootstrap-treeview/

**Comment by jonmiles** [comment]
@mxmissile Thanks for taking the time to sort this one out.
