### ISSUE TITLE
Q: Updating via Web Sockets

### ISSUE THREAD

**Issue by BioCompDevSvcs** [jonmiles/bootstrap-treeview#94]
If I define my data statically in a page and call $('#treeview1').treeview({ data: dataToUse }); such as in your examples, the tree works fine, but when I try to update the tree's data in an "onmessage" function in web sockets by invoking $('#treeview1').treeview({ data: dataToUse }); again with the new data, the tree does not update.  Any suggestions?

**Comment by jonmiles** [comment]
Sounds like an issue with your implementation, not the treeview.  

I would suggest debugging your code, perhaps take a look at the context it's running in and/or verify the data being returned is the correct format.

Check the console for errors, ask a question on stackoverflow.

**Comment by BioCompDevSvcs** [comment]
Yes, my fault.  The data I sent to the page was very subtly malformed.  Thanks.

**Comment by vivek144** [comment]
hiee  i also have same issue...when i use the data being returned (that i printed on console and i copied it) it works fine...but when i return data from any function the tree does not update. Any suggestions?
